name: Auto Commit Personal

# Jalankan workflow ini setiap 15 menit
on:
  schedule:
    - cron: '*/15 * * * *'  # Jalankan setiap 15 menit
  workflow_dispatch:  # Memungkinkan pemicu manual

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ambil seluruh riwayat
          persist-credentials: false  # Jangan gunakan credentials default
      
      # Buat file timestamp
      - name: Buat Timestamp
        run: |
          echo "Commit otomatis pada $(date)" > timestamp.txt
      
      # Commit dan push dengan identitas personal
      - name: Commit dan Push dengan Identitas Personal
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          author_name: ${{ secrets.GIT_USERNAME }}  # Nama GitHub Anda
          author_email: ${{ secrets.GIT_EMAIL }}    # Email GitHub Anda
          message: "Commit otomatis pada $(date +%Y-%m-%d' '%H:%M:%S)"
          branch: ${{ github.ref }}
