name: Auto Commit

# Run this workflow every 3 minutes
on:
  schedule:
    - cron: '*/3 * * * *'  # Run every 3 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper commit history
      
      # Configure Git
      - name: Configure Git
        run: |
          git config --local user.email "coinnyari@gmail.com"
          git config --local user.name "bangpateng"
      
      # Create a timestamp file
      - name: Create Timestamp
        run: |
          echo "Auto commit at $(date)" > timestamp.txt
      
      # Commit the changes
      - name: Commit Changes
        run: |
          git add timestamp.txt
          git commit -m "Auto commit at $(date)"
        continue-on-error: true  # Continue even if no changes to commit
      
      # Push the changes
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
